version: '3.7'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "25432:5432"
    volumes:
      # Required to persist data instead of just starting with fresh postgres install every time.
      - ./docker/data/postgres:/var/lib/postgresql/data
  web:
    build: .
    command: puma
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
