version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: ruby:2.6.6
        environment:
          RAILS_ENV: test
          DATABASE_URL_TEST: postgres://postgres:pwdNOW!@localhost:5432/inventions
      - image: postgres:13
        environment:
          POSTGRES_DB: inventions
          POSTGRES_PASSWORD: pwdNOW!
    executor: ruby/default
    steps:
      - checkout

      - run:
          name: Which bundler?
          command: bundle -v

      - ruby/bundle-install

      - run:
          name: Make rspec results directory
          command: mkdir ~/rspec

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - run:
          name: Run rspec
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml
          when: always

      - store_test_results:
          path: ~/rspec
