version: 2
machine:
  services:
    - docker
jobs:
  build:
    working_directory: ~/inventions-api
    docker: # run the steps with Docker
      - image: mikescar/heroku-ruby-2.5
        environment:
          RAILS_ENV: test
          DATABASE_URL_TEST: postgres://postgres@localhost:5432/postgres
      - image: postgres:10.4
    steps:
      - checkout # git checkout to working directory

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - run:
          name: Make test results directory
          command: mkdir ~/rspec

      # Store bundle cache
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for postgres image
          command: |
            TIMEOUT=10
            until psql $DATABASE_URL_TEST "select 1" > /dev/null 2>&1 || [ $TIMEOUT -eq 0 ]; do
              echo "Waiting for postgres server, $((TIMEOUT--)) remaining attempts..."
              sleep 1
            done

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - run:
          name: Run rspec
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml
          when: always

      - store_test_results:
          path: ~/rspec

      - setup_remote_docker

      # TODO add docker-ce into primary image, remove this; also dockerize a wait for postgres above.
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Build and push Docker image
          # TODO fail this if curl command returns error message!
          command: |
            TAG="registry.heroku.com/${APP_NAME_PRODUCTION}/web"
            docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
            docker build --rm=false -t $TAG .
            IMAGE_ID=$(docker inspect $TAG --format={{.Id}} | cut -d':' -f2)
            echo "Image ID is: $IMAGE_ID"
            docker push $TAG
            curl -n -X PATCH https://api.heroku.com/apps/${APP_NAME_PRODUCTION}/formation \
              -d '{
              "updates": [
                {
                  "type": "web"
                }
              ]
            }' \
              -H "Content-Type: application/json" \
              -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
              -H "Authorization: Bearer $HEROKU_API_KEY"
