version: 2
jobs:
  build:
    working_directory: ~/inventions-api
    docker: # run the steps with Docker
      - image: mikescar/heroku-ruby-2.5
        environment:
          RAILS_ENV: test
          DATABASE_URL_TEST: postgres://postgres@localhost:5432/postgres
      - image: postgres:10.4
    steps:
      - checkout # special step to check out source code to working directory

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - run: mkdir ~/rspec

      # Store bundle cache
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - run:
          name: Run rspec
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml
          when: always

      - store_test_results:
          path: ~/rspec
      # See https://circleci.com/docs/2.0/deployment-integrations/ for example deploy configs
