default: &default
  adapter: postgresql
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  timeout: 5000
  url: <%= ENV.fetch('DATABASE_URL') %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
