default: &default
  adapter: postgresql
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch('BITS_DATABASE_DEVELOPMENT', 'bits-api-development') %>

test:
  <<: *default
  database: <%= ENV.fetch('BITS_DATABASE_TEST', 'bits-api-test') %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
