default: &default
  adapter: postgresql
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  timeout: 5000
  url: <%= ENV.fetch('DATABASE_URL', nil) %>

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL_TEST', nil) %>

production:
  <<: *default
