default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: 'bits-api-development'

test:
  <<: *default
  database: 'bits-api-test'

production:
  <<: *default
  database: db/production.sqlite3
